// packages/web/stories/header/header.component.tsx
import React from "react";

export interface HeaderProps {
  title: string;
  description: string;
}

export const FreudHeaderComponent: React.FC<HeaderProps> = ({
  title,
  description,
}) => (
  <div className="freud-docs-header">
    <div className="header">
      <div className="container">
        <h2 className="title">{title}</h2>
        <p className="description">{description}</p>
      </div>
    </div>
  </div>
);

// packages/web/stories/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'freud-header',
  template: `
    <div class="header">
      <div class="container">
        <h2 class="title">{{title}}</h2>
        <p>{{description}}</p>
      </div>
    </div>
  `,
  styleUrls: ['./header.component.scss']
})
export class FreudHeaderComponent {

  @Input() title!: string;
  @Input() description!: string;
}
